#!/bin/bash

if ! [ -z "$1" ]; then
    tpe=$1
else
    tpe=config
fi

i3_out=/tmp/i3_$tpe
i3_in=~/.i3/*$tpe

for file in $i3_in; do
    echo "# $file"
    cat $file
done >$i3_out
echo $i3_out

# vim: ft=sh


