#!/bin/bash
ask()
{
	while true; do
		echo -n -e "\r\n$1 (Yes/No): " > /dev/stderr
		read -n 1 input
        input=${input,,}
		if [ "$input" = "y" ]; then
			echo "" > /dev/stderr
			return 0
		elif [ "$input" = "a" ]; then
			force="true"
			echo "" > /dev/stderr
			return 0
		elif [ "$input" = "n" ]; then
			echo "" > /dev/stderr
			return 1
		fi
	done;
}

for file in *; do
	if [ "$file" = "$0" ]; then continue; fi
	dotfile=~/.$file
	file=$(pwd)/$file
	if [ -L $dotfile ]; then
	   	if [ "$(readlink $dotfile)" = $file ]; then
			echo "Dotfile \"$dotfile\" already installed."
		else
			if $(ask "\"$dotfile\" already exists (points to \"$(readlink $dotfile)\"). Owerwrite?" ); then
				rm $dotfile
				ln -s $file $dotfile && echo "\"$dotfile\" successfully installed."
			else
				echo "Skip \"$dotfile\"."
			fi
		fi
	elif [ -e $dotfile ]; then
		if $(ask "\"$dotfile\" exists. Owerwrite?"); then
			mv $dotfile $dotfile.bkp &&
			  ln -s $file $dotfile &&
                echo "\"$dotfile\" installed. (backup \"$dotfile.bkp\")"
		else
			echo "Skip \"$dotfile\"."
		fi
	fi
done

# vim: ts=4 sw=4 nu ft=sh
