#!/usr/bin/env bash
###############################################################################
# .nbrc
#
# Configuration file for `nb`, a command line note-taking, bookmarking,
# and knowledge base application with encryption, search, Git-backed syncing,
# and more in a single portable script.
#
# Edit this file manually or manage settings using the `nb settings`
# subcommand. Configuration options are set as environment variables, eg:
#   export NB_ENCRYPTION_TOOL=gpg
#
# https://github.com/xwmx/nb
###############################################################################

export NB_FOOTER="${NB_FOOTER:-0}" # Set by `nb` • Fri Jul 31 03:58:41 PM CEST 2026

export NB_SYNTAX_THEME="${NB_SYNTAX_THEME:-Solarized (light)}" # Set by `nb` • Fri Jul 31 04:42:15 PM CEST 2026
